name:                convert-units
version:             0
github:              "AliceRixte/convert-units"
license:             BSD-3-Clause
author:              "Alice Rixte"
maintainer:          "alice.rixte@u-bordeaux.fr"
copyright:           "(c) Alice Rixte 2025"
synopsis:            Statically typed unit conversions
category:            Physics, Data, Numeric, Math

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AliceRixte/convert-units/blob/main/README.md>


dependencies:
- base >= 4.18 && < 5
# - groups ?
# - data-default ?
- template-haskell >= 2.21.0

ghc-options:
- -Wall
- -threaded

default-extensions:
  - GHC2024
  - NoStarIsType
  - FunctionalDependencies
  - TypeFamilies
  - UndecidableInstances
  - DerivingVia
  - UndecidableInstances
  - TemplateHaskell

library:
  source-dirs: src

tests:
  convert-units-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hspec >= 2.11
    - QuickCheck >= 2.14
    - linear
    - convert-units
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N

benchmarks:
  convert-units-bench:
    main: Main.hs
    dependencies:
      - convert-units
      - criterion >= 1.6
    source-dirs: benchmark
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-N
