name:                convert-units
version:             0.1.0.0
github:              "AliceRixte/convert-units"
license:             LGPL-3
author:              "Alice Rixte"
maintainer:          "alice.rixte@u-bordeaux.fr"
copyright:           "BSD 3"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Arithmetic and type checked conversions between units.
category:

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AliceRixte/convert-units/blob/main/README.md>


dependencies:
- base >= 4.18 && < 5
- hspec
- QuickCheck
- data-default
- convertible
- newtype
- template-haskell

ghc-options:
- -Wall
- -threaded

default-extensions:
  - TypeApplications
  - StandaloneDeriving
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - TypeOperators
  - PolyKinds
  - ScopedTypeVariables
  - DataKinds
  - TypeFamilies
  - FlexibleInstances
  - UndecidableInstances
  - MultiParamTypeClasses
  - FlexibleContexts
  - TemplateHaskell

library:
  ghc-options:
  - -O2 #TODO change

  source-dirs: src


tests:
  convert-units-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hspec >= 2.11
    - QuickCheck >= 2.14
    - linear
    - convert-units
    ghc-options:
    - -O0
    - -rtsopts
    - -with-rtsopts=-N


benchmarks:
  convert-units-bench:
    main: Main.hs
    dependencies:
      - convert-units
      - criterion >= 1.6
    source-dirs: benchmark
    ghc-options:
      - -O2
      - -rtsopts
      - -with-rtsopts=-N